export const standings = [
  {
    league: {
      id: 39,
      name: 'Premier League',
      country: 'England',
      logo: 'https://media.api-sports.io/football/leagues/39.png',
      flag: 'https://media.api-sports.io/flags/gb.svg',
      season: 2022,
      standings: [
        [
          {
            rank: 1,
            team: {
              id: 42,
              name: 'Arsenal',
              logo: 'https://media.api-sports.io/football/teams/42.png',
            },
            points: 63,
            goalsDiff: 34,
            group: 'Premier League',
            form: 'WWWWL',
            status: 'same',
            description: 'Promotion - Champions League (Group Stage)',
            all: {
              played: 26,
              win: 20,
              draw: 3,
              lose: 3,
              goals: {
                for: 59,
                against: 25,
              },
            },
            home: {
              played: 13,
              win: 10,
              draw: 2,
              lose: 1,
              goals: {
                for: 34,
                against: 16,
              },
            },
            away: {
              played: 13,
              win: 10,
              draw: 1,
              lose: 2,
              goals: {
                for: 25,
                against: 9,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 2,
            team: {
              id: 50,
              name: 'Manchester City',
              logo: 'https://media.api-sports.io/football/teams/50.png',
            },
            points: 58,
            goalsDiff: 41,
            group: 'Premier League',
            form: 'WWDWW',
            status: 'same',
            description: 'Promotion - Champions League (Group Stage)',
            all: {
              played: 26,
              win: 18,
              draw: 4,
              lose: 4,
              goals: {
                for: 66,
                against: 25,
              },
            },
            home: {
              played: 13,
              win: 11,
              draw: 1,
              lose: 1,
              goals: {
                for: 43,
                against: 13,
              },
            },
            away: {
              played: 13,
              win: 7,
              draw: 3,
              lose: 3,
              goals: {
                for: 23,
                against: 12,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 3,
            team: {
              id: 33,
              name: 'Manchester United',
              logo: 'https://media.api-sports.io/football/teams/33.png',
            },
            points: 49,
            goalsDiff: 13,
            group: 'Premier League',
            form: 'WWDWL',
            status: 'same',
            description: 'Promotion - Champions League (Group Stage)',
            all: {
              played: 24,
              win: 15,
              draw: 4,
              lose: 5,
              goals: {
                for: 41,
                against: 28,
              },
            },
            home: {
              played: 12,
              win: 9,
              draw: 2,
              lose: 1,
              goals: {
                for: 24,
                against: 8,
              },
            },
            away: {
              played: 12,
              win: 6,
              draw: 2,
              lose: 4,
              goals: {
                for: 17,
                against: 20,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 4,
            team: {
              id: 47,
              name: 'Tottenham',
              logo: 'https://media.api-sports.io/football/teams/47.png',
            },
            points: 45,
            goalsDiff: 10,
            group: 'Premier League',
            form: 'LWWLW',
            status: 'same',
            description: 'Promotion - Champions League (Group Stage)',
            all: {
              played: 26,
              win: 14,
              draw: 3,
              lose: 9,
              goals: {
                for: 46,
                against: 36,
              },
            },
            home: {
              played: 13,
              win: 9,
              draw: 0,
              lose: 4,
              goals: {
                for: 26,
                against: 15,
              },
            },
            away: {
              played: 13,
              win: 5,
              draw: 3,
              lose: 5,
              goals: {
                for: 20,
                against: 21,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 5,
            team: {
              id: 34,
              name: 'Newcastle',
              logo: 'https://media.api-sports.io/football/teams/34.png',
            },
            points: 41,
            goalsDiff: 18,
            group: 'Premier League',
            form: 'LLDDD',
            status: 'same',
            description: 'Promotion - Europa League (Group Stage)',
            all: {
              played: 24,
              win: 10,
              draw: 11,
              lose: 3,
              goals: {
                for: 35,
                against: 17,
              },
            },
            home: {
              played: 12,
              win: 6,
              draw: 5,
              lose: 1,
              goals: {
                for: 19,
                against: 8,
              },
            },
            away: {
              played: 12,
              win: 4,
              draw: 6,
              lose: 2,
              goals: {
                for: 16,
                against: 9,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 6,
            team: {
              id: 40,
              name: 'Liverpool',
              logo: 'https://media.api-sports.io/football/teams/40.png',
            },
            points: 39,
            goalsDiff: 12,
            group: 'Premier League',
            form: 'WDWWL',
            status: 'same',
            description: null,
            all: {
              played: 24,
              win: 11,
              draw: 6,
              lose: 7,
              goals: {
                for: 40,
                against: 28,
              },
            },
            home: {
              played: 12,
              win: 8,
              draw: 3,
              lose: 1,
              goals: {
                for: 27,
                against: 9,
              },
            },
            away: {
              played: 12,
              win: 3,
              draw: 3,
              lose: 6,
              goals: {
                for: 13,
                against: 19,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 7,
            team: {
              id: 36,
              name: 'Fulham',
              logo: 'https://media.api-sports.io/football/teams/36.png',
            },
            points: 39,
            goalsDiff: 5,
            group: 'Premier League',
            form: 'DWWDL',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 11,
              draw: 6,
              lose: 8,
              goals: {
                for: 36,
                against: 31,
              },
            },
            home: {
              played: 13,
              win: 6,
              draw: 4,
              lose: 3,
              goals: {
                for: 21,
                against: 17,
              },
            },
            away: {
              played: 12,
              win: 5,
              draw: 2,
              lose: 5,
              goals: {
                for: 15,
                against: 14,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 8,
            team: {
              id: 51,
              name: 'Brighton',
              logo: 'https://media.api-sports.io/football/teams/51.png',
            },
            points: 38,
            goalsDiff: 14,
            group: 'Premier League',
            form: 'WLDWD',
            status: 'same',
            description: null,
            all: {
              played: 23,
              win: 11,
              draw: 5,
              lose: 7,
              goals: {
                for: 43,
                against: 29,
              },
            },
            home: {
              played: 12,
              win: 6,
              draw: 2,
              lose: 4,
              goals: {
                for: 21,
                against: 11,
              },
            },
            away: {
              played: 11,
              win: 5,
              draw: 3,
              lose: 3,
              goals: {
                for: 22,
                against: 18,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 9,
            team: {
              id: 55,
              name: 'Brentford',
              logo: 'https://media.api-sports.io/football/teams/55.png',
            },
            points: 35,
            goalsDiff: 7,
            group: 'Premier League',
            form: 'DDWDW',
            status: 'same',
            description: null,
            all: {
              played: 23,
              win: 8,
              draw: 11,
              lose: 4,
              goals: {
                for: 37,
                against: 30,
              },
            },
            home: {
              played: 12,
              win: 6,
              draw: 5,
              lose: 1,
              goals: {
                for: 24,
                against: 11,
              },
            },
            away: {
              played: 11,
              win: 2,
              draw: 6,
              lose: 3,
              goals: {
                for: 13,
                against: 19,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 10,
            team: {
              id: 49,
              name: 'Chelsea',
              logo: 'https://media.api-sports.io/football/teams/49.png',
            },
            points: 34,
            goalsDiff: -1,
            group: 'Premier League',
            form: 'WLLDD',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 9,
              draw: 7,
              lose: 9,
              goals: {
                for: 24,
                against: 25,
              },
            },
            home: {
              played: 12,
              win: 6,
              draw: 3,
              lose: 3,
              goals: {
                for: 14,
                against: 8,
              },
            },
            away: {
              played: 13,
              win: 3,
              draw: 4,
              lose: 6,
              goals: {
                for: 10,
                against: 17,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 11,
            team: {
              id: 66,
              name: 'Aston Villa',
              logo: 'https://media.api-sports.io/football/teams/66.png',
            },
            points: 34,
            goalsDiff: -7,
            group: 'Premier League',
            form: 'WWLLL',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 10,
              draw: 4,
              lose: 11,
              goals: {
                for: 31,
                against: 38,
              },
            },
            home: {
              played: 13,
              win: 6,
              draw: 2,
              lose: 5,
              goals: {
                for: 20,
                against: 19,
              },
            },
            away: {
              played: 12,
              win: 4,
              draw: 2,
              lose: 6,
              goals: {
                for: 11,
                against: 19,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 12,
            team: {
              id: 52,
              name: 'Crystal Palace',
              logo: 'https://media.api-sports.io/football/teams/52.png',
            },
            points: 27,
            goalsDiff: -11,
            group: 'Premier League',
            form: 'LDDDL',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 6,
              draw: 9,
              lose: 10,
              goals: {
                for: 21,
                against: 32,
              },
            },
            home: {
              played: 13,
              win: 4,
              draw: 5,
              lose: 4,
              goals: {
                for: 12,
                against: 17,
              },
            },
            away: {
              played: 12,
              win: 2,
              draw: 4,
              lose: 6,
              goals: {
                for: 9,
                against: 15,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 13,
            team: {
              id: 39,
              name: 'Wolves',
              logo: 'https://media.api-sports.io/football/teams/39.png',
            },
            points: 27,
            goalsDiff: -16,
            group: 'Premier League',
            form: 'WLDLW',
            status: 'same',
            description: null,
            all: {
              played: 26,
              win: 7,
              draw: 6,
              lose: 13,
              goals: {
                for: 19,
                against: 35,
              },
            },
            home: {
              played: 13,
              win: 5,
              draw: 2,
              lose: 6,
              goals: {
                for: 10,
                against: 15,
              },
            },
            away: {
              played: 13,
              win: 2,
              draw: 4,
              lose: 7,
              goals: {
                for: 9,
                against: 20,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 14,
            team: {
              id: 65,
              name: 'Nottingham Forest',
              logo: 'https://media.api-sports.io/football/teams/65.png',
            },
            points: 25,
            goalsDiff: -24,
            group: 'Premier League',
            form: 'LDLWD',
            status: 'same',
            description: null,
            all: {
              played: 24,
              win: 6,
              draw: 7,
              lose: 11,
              goals: {
                for: 18,
                against: 42,
              },
            },
            home: {
              played: 12,
              win: 5,
              draw: 4,
              lose: 3,
              goals: {
                for: 15,
                against: 13,
              },
            },
            away: {
              played: 12,
              win: 1,
              draw: 3,
              lose: 8,
              goals: {
                for: 3,
                against: 29,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 15,
            team: {
              id: 46,
              name: 'Leicester',
              logo: 'https://media.api-sports.io/football/teams/46.png',
            },
            points: 24,
            goalsDiff: -7,
            group: 'Premier League',
            form: 'LLLWW',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 7,
              draw: 3,
              lose: 15,
              goals: {
                for: 36,
                against: 43,
              },
            },
            home: {
              played: 12,
              win: 3,
              draw: 3,
              lose: 6,
              goals: {
                for: 15,
                against: 14,
              },
            },
            away: {
              played: 13,
              win: 4,
              draw: 0,
              lose: 9,
              goals: {
                for: 21,
                against: 29,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 16,
            team: {
              id: 48,
              name: 'West Ham',
              logo: 'https://media.api-sports.io/football/teams/48.png',
            },
            points: 23,
            goalsDiff: -10,
            group: 'Premier League',
            form: 'LWLDD',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 6,
              draw: 5,
              lose: 14,
              goals: {
                for: 23,
                against: 33,
              },
            },
            home: {
              played: 12,
              win: 5,
              draw: 2,
              lose: 5,
              goals: {
                for: 16,
                against: 13,
              },
            },
            away: {
              played: 13,
              win: 1,
              draw: 3,
              lose: 9,
              goals: {
                for: 7,
                against: 20,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 17,
            team: {
              id: 63,
              name: 'Leeds',
              logo: 'https://media.api-sports.io/football/teams/63.png',
            },
            points: 22,
            goalsDiff: -11,
            group: 'Premier League',
            form: 'LWLLD',
            status: 'same',
            description: null,
            all: {
              played: 25,
              win: 5,
              draw: 7,
              lose: 13,
              goals: {
                for: 29,
                against: 40,
              },
            },
            home: {
              played: 12,
              win: 4,
              draw: 4,
              lose: 4,
              goals: {
                for: 16,
                against: 16,
              },
            },
            away: {
              played: 13,
              win: 1,
              draw: 3,
              lose: 9,
              goals: {
                for: 13,
                against: 24,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 18,
            team: {
              id: 45,
              name: 'Everton',
              logo: 'https://media.api-sports.io/football/teams/45.png',
            },
            points: 21,
            goalsDiff: -19,
            group: 'Premier League',
            form: 'LLWLW',
            status: 'same',
            description: 'Relegation - Championship',
            all: {
              played: 25,
              win: 5,
              draw: 6,
              lose: 14,
              goals: {
                for: 17,
                against: 36,
              },
            },
            home: {
              played: 13,
              win: 4,
              draw: 2,
              lose: 7,
              goals: {
                for: 11,
                against: 16,
              },
            },
            away: {
              played: 12,
              win: 1,
              draw: 4,
              lose: 7,
              goals: {
                for: 6,
                against: 20,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 19,
            team: {
              id: 41,
              name: 'Southampton',
              logo: 'https://media.api-sports.io/football/teams/41.png',
            },
            points: 21,
            goalsDiff: -21,
            group: 'Premier League',
            form: 'WLWLL',
            status: 'same',
            description: 'Relegation - Championship',
            all: {
              played: 25,
              win: 6,
              draw: 3,
              lose: 16,
              goals: {
                for: 20,
                against: 41,
              },
            },
            home: {
              played: 12,
              win: 2,
              draw: 3,
              lose: 7,
              goals: {
                for: 11,
                against: 19,
              },
            },
            away: {
              played: 13,
              win: 4,
              draw: 0,
              lose: 9,
              goals: {
                for: 9,
                against: 22,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
          {
            rank: 20,
            team: {
              id: 35,
              name: 'Bournemouth',
              logo: 'https://media.api-sports.io/football/teams/35.png',
            },
            points: 21,
            goalsDiff: -27,
            group: 'Premier League',
            form: 'LLWDL',
            status: 'same',
            description: 'Relegation - Championship',
            all: {
              played: 25,
              win: 5,
              draw: 6,
              lose: 14,
              goals: {
                for: 24,
                against: 51,
              },
            },
            home: {
              played: 12,
              win: 3,
              draw: 4,
              lose: 5,
              goals: {
                for: 12,
                against: 16,
              },
            },
            away: {
              played: 13,
              win: 2,
              draw: 2,
              lose: 9,
              goals: {
                for: 12,
                against: 35,
              },
            },
            update: '2023-03-04T00:00:00+00:00',
          },
        ],
      ],
    },
  },
]
